%[number    substance                          formula  ]
%[1         Air                                -        ]
%[2         Ammonia                            NH3      ]
%[3         Argon                              Ar       ]
%[4         Benzene                            C6H6     ]
%[5         Bromine                            Br2      ]
%[6         n-Butane                           C4H10    ]
%[7         Carbon dioxide                     CO2      ]
%[8         Carbon monoxide                    CO       ]
%[9         Carbon tetrachloride               CCl4     ]
%[10        Chlorine                           Cl2      ]
%[11        Chloroform                         CHCl3    ]
%[12        Dichlorodifluoromethane(R-12)      CCl2F2   ]
%[13        Dichlorofluoromethane(R-21)        CHCl2F   ]
%[14        Ethane                             C2H6     ]
%[15        Ethyl alcohol                      C2H5OH   ]
%[16        Ethylene                           C2H4     ]
%[17        Helium                             He       ]
%[18        n-Hexane                           C6H14    ]
%[19        Hydrogen(normal)                   H2       ]
%[20        Krypton                            Kr       ]
%[21        Methane                            CH4      ]
%[22        Methyl alcohol                     CH3OH    ]
%[23        Methyl chloride                    CH3Cl    ]
%[24        Neon                               Ne       ]
%[25        Nitrogen                           N2       ]
%[26        Nitrous oxide                      N2O      ]
%[27        Oxygen                             O2       ]
%[28        n-Pentane                          C5H12    ]
%[29        Propane                            C3H8     ]
%[30        Propylene                          C3H6     ]
%[31        Sulfur dioxide                     SO2      ]
%[32        Tetrafluoroethane(R-134a)          CF3CH2F  ]
%[33        Toluene                            C7H8     ]
%[34        Trichlorofluoromethane(R-11)       CCl3F    ]
%[35        Water                              H2O      ]
%[36        Xenon                              Xe       ]
function propName=PropertieNames(numberInChart)
propNames=["Air","Ammonia","Argon","Benzene","Bromine","n-Butane","Carbon dioxide","Carbon monoxide","Carbon tetrachloride","Chlorine","Chloroform","Dichlorodifluoromethane(R-12)","Dichlorofluoromethane(R-21)","Ethane","Ethyl alcohol","Ethylene","Helium","n-Hexane","Hydrogen","Krypton","Methane","Methyl alcohol","Methyl chloride","Neon","Nitrogen","Nitrous oxide","Oxygen","n-Pentane","Propane","Propylene","Sulfur dioxide","Tetrafluoroethane(R-134a)","Toluene","Trichlorofluoromethane(R-11)","Water","Xenon"];
propName=propNames(numberInChart);